In [3]:
import math
import numpy as np
import pandas as pd

# Ordering:
# NOR, FIR, WAT, ELE, GRA, ICE, FIG, POI, GRO, FLY, PSY, BUG, ROC, GHO, DRA, DAR, STE, FAI
elemental_dict = {
    "normal" : [1,1,1,1,1,1,2,1,1,1,1,1,1,0,1,1,1,1],
    "fire" : [1,0.5,2,1,0.5,0.5,1,1,2,1,1,0.5,2,1,1,1,0.5,0.5],
    "water" : [1,0.5,0.5,2,2,0.5,1,1,1,1,1,1,1,1,1,1,0.5,1],
    "electric" : [1,1,1,0.5,1,1,1,1,2,0.5,1,1,1,1,1,1,0.5,1],
    "grass" : [1,2,0.5,0.5,0.5,2,1,2,0.5,2,1,2,1,1,1,1,1,1],
    "ice" : [1,2,1,1,1,0.5,2,1,1,1,1,1,2,1,1,1,2,1],
    "fighting" : [1,1,1,1,1,1,1,1,1,2,2,0.5,0.5,1,1,0.5,1,2],
    "poison" : [1,1,1,1,0.5,1,0.5,0.5,2,1,2,0.5,1,1,1,1,1,0.5],
    "ground" : [1,1,2,0,2,2,1,0.5,1,1,1,1,0.5,1,1,1,1,1],
    "flying" : [1,1,1,2,0.5,2,0.5,1,0,1,1,0.5,2,1,1,1,1,1],
    "psychic" : [1,1,1,1,1,1,0.5,1,1,1,0.5,2,1,2,1,2,1,1],
    "bug" : [1,2,1,1,0.5,1,0.5,1,0.5,2,1,1,2,1,1,1,1,1],
    "rock" : [0.5,0.5,2,1,2,1,2,0.5,2,0.5,1,1,1,1,1,1,2,1],
    "ghost" : [0,1,1,1,1,1,0,0.5,1,1,1,0.5,1,2,1,2,1,1],
    "dragon" : [1,0.5,0.5,0.5,0.5,2,1,1,1,1,1,1,1,1,2,1,1,2],
    "dark" : [1,1,1,1,1,1,2,1,1,1,0,2,1,0.5,1,0.5,1,2],
    "steel" : [0.5,2,1,1,0.5,0.5,2,0,2,0.5,0.5,0.5,0.5,1,0.5,1,0.5,0.5],
    "fairy" : [1,1,1,1,1,1,0.5,2,1,1,1,0.5,1,1,0,0.5,2,1]
}

def calcHP(base, iv, ev):
    stat = 2 * base + iv + math.floor(ev / 4.0)
    stat = stat * 50
    stat = math.floor(0.01 * stat)
    return stat + 60

def calcStat(base, iv, ev):
    stat = 2 * base + iv + math.floor(ev / 4.0)
    stat = stat * 50
    stat = math.floor(0.01 * stat)
    return stat + 5

def calcBaseDamage(power, atk, defense):
    damage = 22 * power * (atk / defense)
    damage = math.floor(damage / 50)
    return damage + 2

def getAllDamageRolls(totalDamage):
    a = []
    for x in range(85, 101):
        damage = math.floor(totalDamage * x / 100)
        a.append(damage)
    return np.array(a)

def getTypeEffectiveness(atkType, defType1, defType2):
    defArray = elemental_dict[defType1]
    effectiveness1 = defArray[getIndexOfType(atkType)]
    effectiveness2 = 1.0
    if defType2 != "":
        defArray = elemental_dict[defType2]
        effectiveness2 = defArray[getIndexOfType(atkType)]
    return effectiveness1 * effectiveness2

def getIndexOfType(type):
    return list(elemental_dict).index(type)

stab = 1.5

class Pokemon:
    def __init__(self, name, atk, defense, spatk, spdef, speed, type1, type2):
        self.name = name
        self.atk = atk
        self.defense = defense
        self.spatk = spatk
        self.spdef = spdef
        self.speed = speed
        self.type1 = type1
        self.type2 = type2
        
class Move:
    def __init__(self, name, physical, potency, type):
        self.name = name
        self.physical = physical
        self.potency = potency
        self.type = type



In [4]:
move1 = Move("Blizzard", False, 110, "ice")
move2 = Move("Leaf Storm", False, 130, "grass")
move3 = Move("Ice Shard", True, 40, "ice")
move4 = Move("Cross Chop", True, 100, "fighting")

moves = [move1, move2, move3, move4]

poke1 = Pokemon("Abomasnow", 103, 95, 158, 105, 92, "grass", "ice")
poke2 = Pokemon("Snorlax", 130, 128, 76, 134, 50, "normal", "")

for move in moves:
    # Damage Calc
    if move.physical:
        totalDamage = calcBaseDamage(move.potency, poke1.atk, poke2.defense)
    else:
        totalDamage = calcBaseDamage(move.potency, poke1.spatk, poke2.spdef)

    # Weather

    # Critical

    # Random
    damageRolls = getAllDamageRolls(totalDamage)

    # STAB
    if move.type == poke1.type1 or move.type == poke1.type2:
        damageRolls = np.floor(damageRolls * stab)

    # Type effectiveness
    damageRolls = np.floor(damageRolls * getTypeEffectiveness(move.type, poke2.type1, poke2.type2))

    # Burn penalty

    print(move.name)
    print(damageRolls)

Blizzard
[75. 75. 76. 76. 78. 79. 79. 81. 81. 82. 84. 84. 85. 85. 87. 88.]
Leaf Storm
[ 87.  88.  90.  90.  91.  93.  93.  94.  96.  96.  97.  99.  99. 100.
 102. 103.]
Ice Shard
[19. 19. 19. 21. 21. 21. 21. 21. 21. 22. 22. 22. 22. 22. 22. 24.]
Cross Chop
[62. 62. 64. 64. 64. 66. 66. 68. 68. 68. 70. 70. 70. 72. 72. 74.]


In [13]:
calcHP(90, 31, 140)

183